export const SandboxErrorCode = Object.freeze({
    ERR_SANDBOX_NOT_FOUND: 'ERR_SANDBOX_NOT_FOUND',
    ERR_SANDBOX_START_FAILED: 'ERR_SANDBOX_START_FAILED',
    ERR_SANDBOX_EXEC_TIMEOUT: 'ERR_SANDBOX_EXEC_TIMEOUT',
    ERR_SANDBOX_EXEC_FAILED: 'ERR_SANDBOX_EXEC_FAILED',
});
